import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryClientWrapper from "@/common/components/QueryClientWrapper";
import HeaderAdminPage from "@/common/components/HeaderAdminPage";
import FooterUserPage from "@/common/components/FooterUserPage";
import { Toaster } from "react-hot-toast";
import SideBarBreeders from "@/common/components/SideBarBreeders";
import { BREEDERS, TAB_LOGO } from "@/common/constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `GFBIMS - ${BREEDERS}`,
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={TAB_LOGO} />
      <body className={inter.className}>
        <QueryClientWrapper>
          <HeaderAdminPage />
          <Toaster />
          <SideBarBreeders>{children}</SideBarBreeders>
          <FooterUserPage/>
        </QueryClientWrapper>
      </body>
    </html>
  );
}
