import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryClientWrapper from "@/common/components/QueryClientWrapper";
import { Toaster } from "@/common/components/shadcn/ui/sonner";
import HeaderUserPage from "@/common/components/HeaderUserPage";
import FooterUserPage from "@/common/components/FooterUserPage";
import { TAB_LOGO, USER_PAGE } from "@/common/constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `GFBIMS - ${USER_PAGE}`,
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={TAB_LOGO} />
      <body className={inter.className}>
        <div className="flex flex-col w-full">
          <QueryClientWrapper>
            <HeaderUserPage/>
            {children}
            {/* <FooterUserPage/> */}
            <Toaster />
          </QueryClientWrapper>
        </div>
      </body>
    </html>
  );
}
